steps:
  ### Julia ###
  - label: "Run QuantumToolbox.jl benchmarks with CUDA"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
    command: |
      julia --project=benchmark/QuantumToolbox.jl -e 'println("--- Instantiating project ---")
          using Pkg
          Pkg.instantiate()'

      julia --project=benchmark/QuantumToolbox.jl -e 'println("--- Run Benchmarks ---")
          include("benchmark/QuantumToolbox.jl/runbenchmarks.jl")'
    artifact_paths:
      - "benchmark/results/*"
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: "CUDA"
    timeout_in_minutes: 60

  ### Python ###
  - label: "qutip: pip install requirements"
    key: "pip"
    plugins:
      - docker#v5.12.0:
          image: "python:3"
    command: "pip install -r benchmark/qutip/requirements.txt"

  - label: "qutip: run benchmark"
    depends_on: ["pip"]
    plugins:
      - docker#v5.12.0:
          image: "python:3"
    command: "python -m benchmark.qutip.benchmark -v -s"
    artifact_paths:
      - "benchmarks/results/*"
    agents:
      queue: "juliagpu"
      cuda: "*"
    env:
      GROUP: "CUDA"
    timeout_in_minutes: 60

  #- label: "Run dynamiqs benchmarks with CUDA"
  #  ...
  #  env:
  #    GROUP: "CUDA"
