name: Test Benchmarks


on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.buildkite/**'
      - 'benchmark/**'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.buildkite/**'
      - 'benchmark/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review


defaults:
  run:
    # The slightly odd shell call is to force bash to read .bashrc, which is
    # necessary for having conda behave sensibly.  We use bash as the shell even
    # on Windows, since we don't run anything complicated, and it makes
    # things much simpler.
    shell: bash -l {0}


jobs:
  cases:
    name: ${{ matrix.os }}, python${{ matrix.python-version }}, ${{ matrix.case-name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        case-name: [defaults]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: actions-bench
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          miniforge-version: latest

      - name: Install dependencies
        run: |
           mamba install numpy scipy cython
           mamba install pytest pytest-benchmark
           mamba install pandas matplotlib

      - name: Install Qutip
        run: |
           python -m pip install git+https://github.com/qutip/qutip@master

      - name: Package information
        run: |
          mamba list
          python -c "import qutip; qutip.about()"
      - name: Environment information
        run: |
          uname -a
          if [[ "ubuntu-latest" == "${{ matrix.os }}" ]]; then
              hostnamectl
              lscpu
              free -h
          fi

      - name: Run benchmarks
        run: |
          python -m qutip_benchmark.cli.run_benchmarks -v

      - name: Create artefact containing benchmarks
        uses: actions/upload-artifact@v4
        with:
          name: test_benchmarks
          path: .benchmarks
